version: '3'

services:
  database:
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: main
      POSTGRES_PASSWORD: main
      POSTGRES_DB: main
    ports: [ 5432 ]

  redis:
    image: redis:6-alpine
    ports: [ 6379 ]

  rabbitmq:
    image: library/rabbitmq:3.8-management
    ports: [5672, 15672]
